version: "3.8"
services:
  web:
    platform: linux/amd64
    image: processmaker/pm4-core:${PM_VERSION}
    ports:
      - ${PM_APP_PORT}:80
      - ${PM_BROADCASTER_PORT}:6001
    environment:
      - PM_APP_URL
      - PM_APP_PORT
      - PM_BROADCASTER_PORT
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
      - storage:/code/pm4/storage
    links:
      - redis
      - mysql 
    depends_on:
      - mysql
      - redis 
  redis:
    platform: linux/amd64
    image: redis
  mysql:
    platform: linux/amd64
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: processmaker
      MYSQL_USER: pm
      MYSQL_PASSWORD: pass
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
  storage: